[[project]]
title = "Azure Data Engineer Associate"
category = "Azure Certifications"
image = "./config/assets/icons/microsoft-certified-azure-data-engineer-associate.png"
url = "https://learn.microsoft.com/api/credentials/share/en-us/AllanElias-1401/7BB463FF8336FF89?sharingId=EF9D6197CA26569F"

[[project]]
title = "Fabric Analytics Engineer Associate"
category = "Azure Certifications"
image = "./config/assets/icons/Azure-DP-600.png"
url = "https://learn.microsoft.com/api/credentials/share/en-us/AllanElias-1401/CFB4034B0FE1FB6B?sharingId=EF9D6197CA26569F"

[[project]]
title = "Azure AI Engineer Associate"
category = "Azure Certifications"
image = "./config/assets/icons/microsoft-certified-azure-AI-Engineer.PNG"
url = "https://learn.microsoft.com/api/credentials/share/en-us/AllanElias-1401/F0BFC1D12C97907?sharingId=EF9D6197CA26569F"

[[project]]
title = "Azure Data Scientist Associate"
category = "Azure Certifications"
image = "./config/assets/icons/microsoft-certified-azure-data-scientist-associate.png"
url = "https://learn.microsoft.com/api/credentials/share/en-us/AllanElias-1401/ECF9DE8C5A918F9B?sharingId=EF9D6197CA26569F"

[[project]]
title = "Codigo Facilito Downloader"
category = "Python Scripting"
image = "https://imgur.com/kyHrBGk.png"
url = "https://github.com/ivansaul/codigo_facilito_downloader"

[[project]]
title = "Finance"
category = "Web development"
image = "./config/assets/projects/project-1.jpg"
url = "https://github.com/ivansaul/flutter_cinemapedia_app#screenshots"

[[project]]
title = "Orizon"
category = "Web development"
image = "./config/assets/projects/project-2.png"
url = "https://github.com/ivansaul/flutter_todo_app#screenshots"

[[project]]
title = "Fundo"
category = "Web design"
image = "./config/assets/projects/project-3.jpg"
url = "https://github.com/ivansaul/flutter_cinemapedia_app#screenshots"

[[project]]
title = "Brawlhalla"
category = "Applications"
image = "./config/assets/projects/project-4.png"
url = "https://github.com/ivansaul/flutter_coffee_shop_app#screenshots"

[[project]]
title = "DSM."
category = "Web design"
image = "./config/assets/projects/project-5.png"
url = "https://github.com/ivansaul/flutter_todo_app#screenshots"

[[project]]
title = "MetaSpark"
category = "Web design"
image = "./config/assets/projects/project-6.png"
url = "https://github.com/ivansaul/flutter_todo_app#screenshots"

[[project]]
title = "Summary"
category = "Web development"
image = "./config/assets/projects/project-7.png"
url = "https://github.com/ivansaul/codigo_facilito_downloader"

[[project]]
title = "Task Manager"
category = "Applications"
image = "./config/assets/projects/project-8.jpg"
url = "https://github.com/ivansaul/flutter_coffee_shop_app#screenshots"

[[project]]
title = "Arrival"
category = "Web development"
image = "./config/assets/projects/project-9.png"
url = "https://github.com/ivansaul/flutter_cinemapedia_app#screenshots"
