############## Education config #################
#################################################
# [[education]]
# title = "MSc Artificial Intelligence & Machine Learning"
# timeline = "2020 — 2021"
# description = "Duis aute irure dolor in reprehenderit in voluptate, quila voluptas mag odit aut fugit, sed consequuntur magni dolores eos."

[[education]]
title = "BEng Electronic Communication Engineering"
timeline = "2017 — 2020"
description = "Intelligent Systems and Robotics,Digital Signal Processing,Digital Design & Embedded System,Mechatronic Systems Modelling and control,"

[[education]]
title = "MSc Artificial Intelligence & Machine Learning"
timeline = "2020 — 2021"
description = "Machine Learning and Intelligent Data Analysis,Neural Networks,Intelligent robotics ,Computer Vision and Imaging,Mathematics for Artificial Intelligent "


############## Experience config ################
#################################################
[[experience]]
title = "Vaisa Data Analyst Intern"
timeline = "06-2021 — 11-2021"
description = "Extracting, Transforming and Loading (ETL): streaming data from Lidar streaming sensor feed to AWS S3 lakehouse, deploying ML models for weather classification"

[[experience]]
title = "ANS Data Engineer Consultant"
timeline = "2021 — 2023"
description = "Data consultantation : Data migration, Modern Data platform with Azure Synapse Analytics & Microsolf Fabric, Power BI Data Models & reporting"

[[experience]]
title = "Capita Data Engineer"
timeline = "2023 — Present"
description = "Build, Deplying and managing data platform with Azure DevOps, ETL Data with Azure Data factory & Synapse Analytics, Cloud Data migration, SQL-Server Database Design "


############## Skills config ####################
#################################################
[skills]
title = "My Skills"
enabled = true
show_bar = true
show_value = true

[[skill]]
title = "Azure Data Factory:"
value = "90%"

[[skill]]
title = "Azure Synapse Analytics: T-SQL, PySpark"
value = "90%"

[[skill]]
title = "Azure Databricks:Apache Spark, Delta Lake, MLflow, REST API"
value = "90%"

[[skill]]
title = "Microsoft Fabric: lakehouse, Notebooks, ML models, BI Tools"
value = "80%"

[[skill]]
title = "Power BI: Data Modelling, Power Query, DAX"
value = "80%"

############## Language config ##################
#################################################
[languages]
title = "Languages"
enabled = false
show_bar = true
show_value = true

[[language]]
title = "English"
value = "90%"

[[language]]
title = "other"
value = "50%"
