############### Section config ##################
#################################################
title = "Certified Experience"
enabled = true                 # false

############### Technologies ####################
#################################################
# Technology I have worked with
# name = "./.../../icon_path"
[technologies]
data_factory = "./config/assets/icons/10126-service-Data-Factories.svg"
databricks = "./config/assets/icons/10787-service-Azure-Databricks.svg"
machinelearning = "./config/assets/icons/10166-service-Machine-Learning.svg"
logicApps = "./config/assets/icons/02631-service-Logic-Apps.svg"
python = "./config/assets/icons/python.svg"
pandas = "./config/assets/icons/pandas.svg"
# mongodb = "./config/assets/icons/mongodb.svg"
# dart = "./config/assets/icons/dart.svg"
# html = "./config/assets/icons/html.svg"
# ai = "./config/assets/icons/ai.svg"
# jupyter = "./config/assets/icons/jupyter.svg"
# linux = "./config/assets/icons/linux.svg"
